### ISSUE TITLE
Real code

### ISSUE THREAD

**Issue by birb57** [dmccuk/vm_customisation#1]
Hi Dennis
Can you provide your reak code with full feature?
Thanks

**Comment by dmccuk** [comment]
Hi,
Which feature do you need the code for? If I've missed it off I'll add it in.
Thanks
Dennis

**Comment by birb57** [comment]
Hi Dennis
Lv and filesystem creation
nfs share and mount 
Thanks

**Comment by birb57** [comment]
Hi
In common group_vars we can read :
# My real code add the following:

What do you mean by real ?

Thanks for your support

**Comment by dmccuk** [comment]
Hi,

I have a version of this code running that does quite a lot more but because adding NFS mounts and setting VGs, LVs & FS need an NFS server and I've no additional disk to add, I'm not able to add these features to the code because they won't work.

You just need to add them yourself under either "common" or one of the roles as an "nfs_mount.yml" file. Then make sure you add the new playbook to the main.yml file so it gets run. You can use this as a reference:

Depending on if you use the collection:
https://docs.ansible.com/ansible/2.9/modules/mount_module.html
or
https://docs.ansible.com/ansible/latest/collections/ansible/posix/mount_module.html

for VG,LV & FS setup, use:
https://docs.ansible.com/ansible/2.5/modules/lvol_module.html
https://docs.ansible.com/ansible/2.5/modules/filesystem_module.html

Good luck.

**Comment by birb57** [comment]
Will do it
Thanks for your feedback

**Comment by dmccuk** [comment]
I'll close this issue as resolved. Let me know if you get stuck.
